# Generated by Django 5.2.16 on 2026-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.TextField()),
                ('is_correct', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answer_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('difficulty', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranslatedAnswers',
            fields=[
                ('pk', models.CompositePrimaryKey('answer_id', 'language', blank=True, editable=False, primary_key=True, serialize=False)),
                ('language', models.TextField(blank=True)),
                ('translated_title', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'translated_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranslatedQuestions',
            fields=[
                ('pk', models.CompositePrimaryKey('question_id', 'language', blank=True, editable=False, primary_key=True, serialize=False)),
                ('language', models.TextField(blank=True)),
                ('translated_title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'translated_questions',
                'managed': False,
            },
        ),
    ]
