# Generated by Django 5.2.16 on 2026-07-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.TextField()),
                ('user_name', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('role', models.TextField()),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.users')),
                ('best_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('played', models.IntegerField(blank=True, null=True)),
                ('won', models.IntegerField(blank=True, null=True)),
                ('language', models.TextField()),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': False,
            },
        ),
    ]
