# Generated by Django 5.2.16 on 2026-07-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='statistics', serialize=False, to='users.users')),
                ('best_points', models.IntegerField(blank=True, null=True)),
                ('overall_points', models.IntegerField(blank=True, null=True)),
                ('played', models.IntegerField(blank=True, null=True)),
                ('won', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_statistics',
            },
        ),
    ]
