# Generated by Django 5.2.16 on 2026-07-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='best_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='overall_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
