# Generated by Django 5.2.16 on 2026-07-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userstatistics_best_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistics',
            old_name='best_points',
            new_name='played_count',
        ),
        migrations.RenameField(
            model_name='userstatistics',
            old_name='played',
            new_name='record_points',
        ),
        migrations.RenameField(
            model_name='userstatistics',
            old_name='won',
            new_name='won_count',
        ),
    ]
