# Generated by Django 5.2.16 on 2026-07-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_best_points_userstatistics_played_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to='users.users'),
        ),
    ]
