# Generated by Django 5.2.16 on 2026-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.TextField(blank=True, null=True)),
                ('is_correct', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.TextField(blank=True, null=True)),
                ('finished_at', models.TextField(blank=True, null=True)),
                ('spent_time', models.FloatField(blank=True, null=True)),
                ('help_change_quest', models.IntegerField(blank=True, null=True)),
                ('help_50_50', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'game_sessions',
                'managed': False,
            },
        ),
    ]
